# Generated by Django 5.2.2 on 2025-06-27 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('oficio', models.CharField(max_length=100)),
                ('precio_real', models.FloatField()),
                ('precio_trato', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('impuesto_porcentaje', models.FloatField()),
                ('porcentaje_ganancia', models.FloatField()),
                ('max_trabajadores', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaNoLaborable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('razon', models.CharField(default='No especificado', max_length=255)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_no_laborables', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='contratos.contrato')),
                ('semana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='contratos.semana')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('oficio', models.CharField(max_length=100)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('unidades', models.PositiveIntegerField(default=0)),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.semana')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.trabajador')),
            ],
        ),
    ]
